# Simple Mean-Reverting Model with and without Transaction Costs

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
startDate=20060101

In [4]:
endDate=20061231

In [5]:
df=pd.read_table('SPX_20071123.txt')

In [6]:
df['Date']=df['Date'].astype('int')

In [7]:
df.set_index('Date', inplace=True)

In [8]:
df.sort_index(inplace=True)

In [9]:
df

A       AA      AAPL      ABC    ABI      ABK      ABT  \
Date                                                                     
19991124  41.1250  20.3772   23.6563   5.9980    NaN  31.1549  22.8971   
19991126  41.1875  20.6142   23.7656   5.9980    NaN  31.1183  22.5998   
19991129  42.0000  20.5352   23.6406   5.9675    NaN  30.6418  23.0086   
19991130  42.1875  20.6932   24.4688   6.0284    NaN  31.9613  22.5998   
19991201  43.0000  21.1078   25.7656   6.0588    NaN  33.5740  22.2652   
...           ...      ...       ...      ...    ...      ...      ...   
20071116  36.7200  36.3100  166.3900  44.9800  34.12  27.4600  55.2100   
20071119  35.8000  35.0700  163.9500  43.6900  33.17  25.5300  54.8200   
20071120  36.5100  35.3800  168.8500  44.3200  33.54  24.7900  55.5800   
20071121  36.7000  35.1700  168.4600  43.5200  33.15  24.1400  54.7300   
20071123  36.9100  35.1500  171.5400  43.8900  33.14  25.5500  55.4900   

             ACAS      ACE      ACS  ...      XEL       XL     XLNX      XOM  \
Date                                 ...                                       
19991124   7.6786  12.8492  19.0000  ...  14.8614  38.5249  43.8110  35.1539   
19991126   7.6320  12.8492  18.7188  ...  14.9079  38.5249  43.5356  34.6541   
19991129   7.5855  12.2246  18.7188  ...  14.8614  38.2478  46.8092  35.2650   
19991130   7.4925  12.1353  18.7188  ...  15.0926  37.6935  43.8110  35.2372   
19991201   7.5390  12.2692  18.7188  ...  15.0460  37.7859  43.7804  36.3201   
...           ...      ...      ...  ...      ...      ...      ...      ...   
20071116  38.9200  58.1600  41.7800  ...  22.1500  63.2000  22.9700  85.1000   
20071119  37.5500  57.6300  40.8100  ...  22.1300  58.8700  22.6900  84.1100   
20071120  37.5900  57.3500  40.7300  ...  22.1400  55.6600  21.9500  87.8200   
20071121  37.0900  57.9500  40.3900  ...  22.1000  51.0300  21.5900  87.0200   
20071123  37.7900  58.7800  41.4300  ...  22.1600  52.9900  21.6900  88.2900   

              XRX      XTO     YHOO      YUM     ZION    ZMH  
Date                                                          
19991124  26.7738   2.2456  57.7500  10.0716  51.6312    NaN  
19991126  26.7738   2.2215  56.7188   9.8871  51.6826    NaN  
19991129  26.2989   2.0403  56.5313   9.9640  50.7074    NaN  
19991130  25.7052   1.9679  53.1875  10.2100  53.0170    NaN  
19991201  25.3584   1.9317  57.2188  10.0101  53.6329    NaN  
...           ...      ...      ...      ...      ...    ...  
20071116  15.8200  63.5800  26.8200  38.0700  51.9500  65.38  
20071119  16.0800  62.5600  26.7600  37.8000  50.2200  65.79  
20071120  16.2300  63.5500  26.7200  37.8700  50.0400  64.24  
20071121  16.0900  62.2200  25.7100  37.2100  50.2500  63.48  
20071123  16.5600  63.6500  26.1300  37.6500  52.0000  64.55  

[2024 rows x 500 columns]

In [10]:
dailyret=df.pct_change()

In [11]:
dailyret

A        AA      AAPL       ABC       ABI       ABK  \
Date                                                                   
19991124       NaN       NaN       NaN       NaN       NaN       NaN   
19991126  0.001520  0.011631  0.004620  0.000000       NaN -0.001175   
19991129  0.019727 -0.003832 -0.005260 -0.005085       NaN -0.015313   
19991130  0.004464  0.007694  0.035033  0.010205       NaN  0.043062   
19991201  0.019259  0.020036  0.052998  0.005043       NaN  0.050458   
...            ...       ...       ...       ...       ...       ...   
20071116  0.089614 -0.000551  0.012721  0.013748 -0.003796 -0.027620   
20071119 -0.025054 -0.034150 -0.014664 -0.028679 -0.027843 -0.070284   
20071120  0.019832  0.008839  0.029887  0.014420  0.011155 -0.028986   
20071121  0.005204 -0.005936 -0.002310 -0.018051 -0.011628 -0.026220   
20071123  0.005722 -0.000569  0.018283  0.008502 -0.000302  0.058409   

               ABT      ACAS       ACE       ACS  ...       XEL        XL  \
Date                                              ...                       
19991124       NaN       NaN       NaN       NaN  ...       NaN       NaN   
19991126 -0.012984 -0.006069  0.000000 -0.014800  ...  0.003129  0.000000   
19991129  0.018089 -0.006093 -0.048610  0.000000  ... -0.003119 -0.007193   
19991130 -0.017767 -0.012260 -0.007305  0.000000  ...  0.015557 -0.014492   
19991201 -0.014805  0.006206  0.011034  0.000000  ... -0.003088  0.002451   
...            ...       ...       ...       ...  ...       ...       ...   
20071116  0.013399 -0.027729 -0.011389 -0.002864  ...  0.004535 -0.047476   
20071119 -0.007064 -0.035200 -0.009113 -0.023217  ... -0.000903 -0.068513   
20071120  0.013864  0.001065 -0.004859 -0.001960  ...  0.000452 -0.054527   
20071121 -0.015293 -0.013301  0.010462 -0.008348  ... -0.001807 -0.083184   
20071123  0.013886  0.018873  0.014323  0.025749  ...  0.002715  0.038409   

              XLNX       XOM       XRX       XTO      YHOO       YUM  \
Date                                                                   
19991124       NaN       NaN       NaN       NaN       NaN       NaN   
19991126 -0.006286 -0.014217  0.000000 -0.010732 -0.017856 -0.018319   
19991129  0.075194  0.017629 -0.017737 -0.081567 -0.003306  0.007778   
19991130 -0.064052 -0.000788 -0.022575 -0.035485 -0.059150  0.024689   
19991201 -0.000698  0.030732 -0.013491 -0.018395  0.075794 -0.019579   
...            ...       ...       ...       ...       ...       ...   
20071116 -0.003038  0.007220  0.000000  0.025649  0.055075  0.007143   
20071119 -0.012190 -0.011633  0.016435 -0.016043 -0.002237 -0.007092   
20071120 -0.032613  0.044109  0.009328  0.015825 -0.001495  0.001852   
20071121 -0.016401 -0.009110 -0.008626 -0.020928 -0.037799 -0.017428   
20071123  0.004632  0.014594  0.029211  0.022983  0.016336  0.011825   

              ZION       ZMH  
Date                          
19991124       NaN       NaN  
19991126  0.000996       NaN  
19991129 -0.018869       NaN  
19991130  0.045548       NaN  
19991201  0.011617       NaN  
...            ...       ...  
20071116 -0.002305 -0.011491  
20071119 -0.033301  0.006271  
20071120 -0.003584 -0.023560  
20071121  0.004197 -0.011831  
20071123  0.034826  0.016856  

[2024 rows x 500 columns]

In [12]:
marketDailyret=dailyret.mean(axis=1)

In [13]:
marketDailyret

Date
19991124         NaN
19991126   -0.001131
19991129   -0.010252
19991130   -0.000814
19991201    0.002520
              ...   
20071116    0.001130
20071119   -0.020675
20071120    0.000076
20071121   -0.014486
20071123    0.019083
Length: 2024, dtype: float64

In [14]:
weights=-(np.array(dailyret)-np.array(marketDailyret).reshape((dailyret.shape[0], 1)))

In [15]:
weights

array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [-0.00265099, -0.01276188, -0.00575156, ...,  0.01718761,
        -0.00212675,         nan],
       [-0.02997868, -0.00641951, -0.00499211, ..., -0.01802963,
         0.0086172 ,         nan],
       ...,
       [-0.01975687, -0.00876393, -0.02981163, ..., -0.00177632,
         0.00365976,  0.02363534],
       [-0.01969048, -0.00855087, -0.01217668, ...,  0.00294162,
        -0.01868307, -0.00265579],
       [ 0.01336049,  0.01965123,  0.00079929, ...,  0.00725779,
        -0.0157433 ,  0.00222686]])

In [16]:
wtsum=np.nansum(abs(weights), axis=1)

In [17]:
wtsum

array([0.        , 5.51772376, 8.62801143, ..., 8.1433497 , 6.33286844,
       5.77799263])

In [18]:
weights[wtsum==0,]=0

In [19]:
weights

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00265099, -0.01276188, -0.00575156, ...,  0.01718761,
        -0.00212675,         nan],
       [-0.02997868, -0.00641951, -0.00499211, ..., -0.01802963,
         0.0086172 ,         nan],
       ...,
       [-0.01975687, -0.00876393, -0.02981163, ..., -0.00177632,
         0.00365976,  0.02363534],
       [-0.01969048, -0.00855087, -0.01217668, ...,  0.00294162,
        -0.01868307, -0.00265579],
       [ 0.01336049,  0.01965123,  0.00079929, ...,  0.00725779,
        -0.0157433 ,  0.00222686]])

In [20]:
wtsum[wtsum==0]=1

In [21]:
wtsum

array([1.        , 5.51772376, 8.62801143, ..., 8.1433497 , 6.33286844,
       5.77799263])

In [22]:
weights=weights/wtsum.reshape((dailyret.shape[0],1))

In [23]:
weights

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.00048045, -0.00231289, -0.00104238, ...,  0.00311498,
        -0.00038544,         nan],
       [-0.00347458, -0.00074403, -0.00057859, ..., -0.00208966,
         0.00099875,         nan],
       ...,
       [-0.00242614, -0.00107621, -0.00366086, ..., -0.00021813,
         0.00044942,  0.00290241],
       [-0.00310925, -0.00135024, -0.00192277, ...,  0.0004645 ,
        -0.00295017, -0.00041937],
       [ 0.00231231,  0.00340105,  0.00013833, ...,  0.00125611,
        -0.0027247 ,  0.0003854 ]])

In [24]:
dailypnl=np.nansum(np.array(pd.DataFrame(weights).shift())*np.array(dailyret), axis=1)

In [25]:
dailypnl=dailypnl[np.logical_and(df.index >= startDate, df.index <= endDate)]

In [26]:
dailypnl

array([-4.66815468e-03, -1.45861481e-03,  1.96027706e-03,  3.36467425e-03,
        4.28405029e-04,  1.90432247e-04, -1.75299240e-03, -9.71215014e-04,
        1.43081413e-03, -3.20137628e-03,  2.01528970e-03, -1.52008566e-03,
        5.17453261e-04,  8.01345646e-04, -1.11645742e-03, -2.77046854e-03,
       -5.19190754e-04,  1.18752856e-03,  1.23514048e-03,  4.34253319e-04,
        3.20724130e-03, -4.50239838e-04,  7.27512356e-04, -8.05609000e-04,
        1.06119560e-02, -3.23931344e-03,  1.42195115e-03, -4.85454473e-05,
        1.21236128e-03,  3.57113618e-03, -4.10840221e-03,  3.41305940e-03,
       -1.74247968e-03, -4.88688102e-03,  8.48465068e-03,  5.68013274e-04,
       -1.68127624e-04,  1.94036995e-03,  1.34175932e-03, -8.33359356e-04,
       -3.20844855e-03, -3.07494448e-03,  1.94147929e-04, -2.27399135e-03,
       -9.12257152e-04,  2.71534421e-04, -1.94732518e-03,  4.06037261e-03,
       -1.58766983e-03,  7.13845551e-04,  1.17205050e-03,  1.38649186e-03,
       -2.10930578e-03,  

In [27]:
sharpeRatio=np.sqrt(252)*np.mean(dailypnl)/np.std(dailypnl)

In [28]:
sharpeRatio

0.9577856810103852

# With transaction costs

In [29]:
onewaytcost=0.0005

In [30]:
weights=weights[np.logical_and(df.index >= startDate, df.index <= endDate)]

In [31]:
dailypnlminustcost=dailypnl - (np.nansum(abs(weights-np.array(pd.DataFrame(weights).shift())), axis=1)*onewaytcost)

In [32]:
sharpeRatioMinusTcost=np.sqrt(252)*np.mean(dailypnlminustcost)/np.std(dailypnlminustcost)

In [33]:
sharpeRatioMinusTcost

-2.161743371896228